services:
  fastttsr:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: fhrozen/fast-ttsr:latest
    ports:
      - "${HOST_PORT:-5768}:${HTTP_PORT:-5768}"
    environment:
      HTTP_PORT: ${HTTP_PORT:-5768}
      HTTPS_PORT: ${HTTPS_PORT:-}
      MODEL_CACHE_DIR: /cache
      ESPEAK_DATA_DIR: /app/assets/espeak-ng-data
    volumes:
      - ./model-cache:/cache
      - ./assets:/app/assets:ro
