// Preset text content for demo buttons - 31 languages × 3 presets
export interface PresetTexts {
  quote: Record<string, string>
  paragraph: Record<string, string>
  script: Record<string, string>
}

export const presetTexts: PresetTexts = {
  quote: {
    en: "This text-to-speech system runs entirely in your browser, providing fast and private operation without sending any data to external servers.",
    es: "Este sistema de conversión de texto a voz funciona completamente de forma local en el navegador y procesa todos los datos en el dispositivo para ofrecer un rendimiento rápido y seguro.",
    pt: "Este sistema de conversão de texto em fala funciona totalmente de forma local no navegador, processando todos os dados no próprio dispositivo para garantir desempenho rápido e seguro.",
    fr: "Ce système de synthèse vocale fonctionne entièrement en local dans le navigateur et traite toutes les données sur l'appareil afin d'offrir des performances rapides et sécurisées.",
    ko: "이 텍스트 음성 변환 시스템은 브라우저에서 완전히 로컬로 동작하며, 모든 데이터를 기기 내에서 처리해 안전하고 빠른 성능을 제공합니다.",
    ja: "このテキスト読み上げシステムは完全にブラウザ内で動作し、外部サーバーにデータを送信せずに高速でプライベートな操作を提供します。",
    ar: "يعمل نظام تحويل النص إلى كلام هذا بالكامل داخل متصفحك، ويوفر تشغيلاً سريعاً وخاصاً دون إرسال أي بيانات إلى خوادم خارجية.",
    bg: "Тази система за преобразуване на текст в реч работи изцяло във вашия браузър.",
    cs: "Tento systém pro převod textu na řeč běží zcela ve vašem prohlížeči.",
    da: "Dette tekst-til-tale-system kører udelukkende i din browser.",
    de: "Dieses Sprachsynthese-System läuft vollständig in Ihrem Browser.",
    el: "Αυτό το σύστημα μετατροπής κειμένου σε ομιλία λειτουργεί εξ ολοκλήρου μέσα στον περιηγητή σας.",
    et: "See teksti kõneks muutmise süsteem töötab täielikult teie veebilehitsejas.",
    fi: "Tämä tekstistä puheeksi -järjestelmä toimii kokonaan selaimessasi.",
    hi: "यह टेक्स्ट-टू-स्पीच सिस्टम पूरी तरह से आपके ब्राउज़र में चलता है।",
    hr: "Ovaj sustav pretvaranja teksta u govor radi u potpunosti unutar vašeg preglednika.",
    hu: "Ez a szövegfelolvasó rendszer teljes egészében a böngészőjében fut.",
    id: "Sistem text-to-speech ini berjalan sepenuhnya di browser Anda.",
    it: "Questo sistema di sintesi vocale funziona interamente nel tuo browser.",
    lt: "Ši teksto vertimo į kalbą sistema veikia visiškai jūsų naršyklėje.",
    lv: "Šī teksta pārveidošanas runā sistēma darbojas pilnībā jūsu pārlūkā.",
    nl: "Dit tekst-naar-spraaksysteem werkt volledig in uw browser.",
    pl: "Ten system zamiany tekstu na mowę działa w całości w przeglądarce.",
    ro: "Acest sistem de conversie a textului în vorbire rulează în întregime în browserul dumneavoastră.",
    ru: "Эта система синтеза речи работает полностью в вашем браузере.",
    sk: "Tento systém prevodu textu na reč beží celkom vo vašom prehliadači.",
    sl: "Ta sistem za pretvorbo besedila v govor deluje v celoti v vašem brskalniku.",
    sv: "Detta text-till-tal-system körs helt och hållet i din webbläsare.",
    tr: "Bu metinden konuşmaya dönüştürme sistemi tamamen tarayıcınızda çalışır.",
    uk: "Ця система синтезу мовлення працює повністю у вашому браузері.",
    vi: "Hệ thống chuyển văn bản thành giọng nói này chạy hoàn toàn trong trình duyệt của bạn."
  },
  paragraph: {
    en: "Flat white and cafe latte are both espresso-based drinks with milk. However, they differ clearly in the amount and texture of the milk, as well as in overall flavor balance.",
    es: "El flat white y el café con leche son bebidas a base de espresso con leche. Sin embargo, difieren claramente en la cantidad y textura de la leche, así como en el equilibrio general del sabor.",
    pt: "O flat white e o café com leite são ambos bebidas à base de espresso com leite. No entanto, diferem claramente na quantidade e textura do leite, bem como no equilíbrio geral do sabor.",
    fr: "Le flat white et le café au lait sont tous deux des boissons à base d'espresso avec du lait. Cependant, ils diffèrent clairement dans la quantité et la texture du lait, ainsi que dans l'équilibre général des saveurs.",
    ko: "플랫 화이트와 카페라테는 모두 에스프레소에 우유를 넣은 음료입니다. 하지만 우유의 양과 질감, 그리고 전체적인 맛의 균형에서 명확하게 차이가 있습니다.",
    ja: "フラットホワイトとカフェラテはどちらもエスプレッソに牛乳を加えた飲み物です。しかし、牛乳の量や質感、そして全体的な風味のバランスには明確な違いがあります。",
    ar: "فلات وايت وكافيه لاتيه كلاهما من المشروبات القائمة على الإسبريسو مع الحليب.",
    bg: "Флет уайт и кафе лате са кафета на основата на еспресо с мляко.",
    cs: "Flat white a caffè latte jsou oba nápoje na báze espressa s mlékem.",
    da: "Flat white og caffè latte er begge espressobaserede drikke med mælk.",
    de: "Flat White und Caffè Latte sind beides Espresso-basierte Milchgetränke.",
    el: "Το flat white και ο café latte είναι ροφήματα με βάση το espresso και γάλα.",
    et: "Flat white ja kohvilatte on mõlemad piimaga espresso baasil joogid.",
    fi: "Flat white ja kahvilatte ovat molemmat espresso-pohjaisia juomia, joissa on maitoa.",
    hi: "फ्लैट व्हाइट और कैफे लाते दोनों ही दूध के साथ एस्प्रेसो पर आधारित पेय हैं।",
    hr: "Flat white i caffè latte oba su napitci na bazi espressa s mlijekom.",
    hu: "A flat white és a tejeskávé egyaránt espresso-alapú italok tejjel.",
    id: "Flat white dan cafe latte keduanya adalah minuman berbasis espresso dengan susu.",
    it: "Il flat white e il caffè latte sono entrambe bevande a base di espresso con latte.",
    lt: "Flat white ir caffè latte yra ant espreso pagrįsti gėrimai su pienu.",
    lv: "Flat white un caffè latte abi ir espresso bāzes dzērieni ar pienu.",
    nl: "Flat white en café latte zijn beide op espresso gebaseerde dranken met melk.",
    pl: "Flat white i caffè latte to napoje na bazie espresso z mlekiem.",
    ro: "Flat white și café latte sunt ambele băuturi pe bază de espresso cu lapte.",
    ru: "Флэт уайт и кофе латте — это напитки на основе эспрессо с молоком.",
    sk: "Flat white a caffè latte sú obidva nápoje na báze espressa s mliekom.",
    sl: "Flat white in caffè latte sta oba pijač na osnovi espressa z mlekom.",
    sv: "Flat white och caffè latte är båda espressobaserade drycker med mjölk.",
    tr: "Flat white ve caffè latte ikisi de süt ile yapılan espresso bazlı içeceklerdir.",
    uk: "Флет вайт і кава латте — це обидва напої на основі еспресо з молоком.",
    vi: "Flat white và cafe latte đều là đồ uống dựa trên espresso với sữa."
  },
  script: {
    en: "Hello. Today, I would like to talk about one of the long-standing philosophical debates: Which came first, the chicken or the egg? This question may seem like simple curiosity, but it allows us to deeply explore how we understand life, evolution, cause, and effect.",
    es: "Hola. Hoy me gustaría hablar de uno de los debates filosóficos más antiguos: ¿Qué fue primero, la gallina o el huevo? Esta pregunta puede parecer una simple curiosidad, pero nos permite reflexionar profundamente sobre cómo entendemos la vida y la evolución.",
    pt: "Olá. Hoje gostaria de falar sobre um dos debates filosóficos mais antigos: O que veio primeiro, o ovo ou a galinha? Esta pregunta pode parecer apenas uma curiosidade, mas permite-nos refletir profundamente sobre como entendemos a vida.",
    fr: "Bonjour. Aujourd'hui, j'aimerais aborder l'un des débats philosophiques les plus anciens : Qui est arrivé en premier, la poule ou l'œuf? Cette question peut sembler une simple curiosité, mais elle nous permet de réfléchir en profondeur.",
    ko: "안녕하세요. 오늘은 오랜 철학적 논쟁 중 하나인 닭이 먼저냐 달걀이 먼저냐에 대해 이야기하고 싶습니다. 이 질문은 단순한 호기심처럼 보일 수 있지만, 생명과 진화를 어떻게 이해하는지 깊이 탐구할 수 있게 해줍니다.",
    ja: "こんにちは。今日は、長い歴史を持つ哲学的な議論のひとつ、鶏が先か、卵が先かについてお話ししたいと思います。この質問は単なる好奇心のように見えるかもしれませんが、実は私たちが生命や進化をどのように理解しているのかを深く考えさせてくれるテーマです。",
    ar: "مرحباً. أود اليوم أن أتحدث عن واحد من أقدم الجدالات الفلسفية: أيهما جاء أولاً، الدجاجة أم البيضة؟",
    bg: "Здравейте. Днес бих искал да поговоря за един от най-старите философски спорове: Кое е било първо — кокошката или яйцето?",
    cs: "Dobrý den. Dnes bych rád mluvil o jedné z nejstarších filosofických debat: Co bylo dříve, slepice, nebo vejce?",
    da: "Goddag. I dag vil jeg gerne tale om en af de længstvarende filosofiske debatter: Hvad kom først, hønen eller ægget?",
    de: "Hallo. Heute möchte ich über eine der ältesten philosophischen Debatten sprechen: Was war zuerst da, das Huhn oder das Ei?",
    el: "Γεια σας. Σήμερα θα ήθελα να μιλήσω για μία από τις παλαιότερες φιλοσοφικές συζητήσεις: Τι ήταν πρώτο, η κότα ή το αυγό;",
    et: "Tere. Täna sooviksin rääkida ühest kõige pikemaajalisemast filosoofilisest arutelust: Mis oli enne, kana või muna?",
    fi: "Hei. Tänään haluaisin puhua yhdestä pisimpään jatkuneista filosofisista keskusteluista: Kumpi oli ensin, kana vai muna?",
    hi: "नमस्ते। आज मैं एक पुराने दार्शनिक विवाद के बारे में बात करना चाहता हूँ: पहले मुर्गी आई या अंडा?",
    hr: "Dobar dan. Danas bih želio govoriti o jednoj od najstarijih filozofskih rasprava: Što je bilo prije, kokoš ili jaje?",
    hu: "Jó napot. Ma szeretnék beszélni az egyik legrégebbi filozófiai vitáról: Mi volt előbb, a tyúk vagy a tojás?",
    id: "Halo. Hari ini saya ingin berbicara tentang salah satu perdebatan filosofis paling lama: Mana yang lebih dulu, ayam atau telur?",
    it: "Salve. Oggi vorrei parlare di uno dei dibattiti filosofici più antichi: Cosa è venuto prima, la gallina o l'uovo?",
    lt: "Sveiki. Šiandien norėčiau pakalbėti apie vieną iš ilgiausiai trunkančių filosofinių diskusijų: Kas buvo pirmiau, višta ar kiaušinis?",
    lv: "Sveiki. Šodien es vēlētos runāt par vienu no ilgākajām filozofiskajām diskusijām: Kas bija agrāk, vista vai ola?",
    nl: "Hallo. Vandaag wil ik graag praten over een van de oudste filosofische debatten: Wat was er eerst, de kip of het ei?",
    pl: "Dzień dobry. Dziś chciałbym porozmawiać o jednym z najdłużej trwających sporów filozoficznych: Co było pierwsze, kura czy jajko?",
    ro: "Bună ziua. Astăzi aș dori să vorbesc despre una dintre cele mai vechi dezbateri filosofice: Ce a fost prima dată, găina sau oul?",
    ru: "Здравствуйте. Сегодня я хотел бы поговорить об одном из старейших философских споров: Что было первым, курица или яйцо?",
    sk: "Dobrý deň. Dnes by som chcel hovoriť o jednej z najstarších filozofických debát: Čo bolo skôr, sliepka alebo vajce?",
    sl: "Dober dan. Danes bi rad govoril o eni najstarejših filozofskih razprav: Kaj je bilo prej, kokoš ali jajce?",
    sv: "Hej. Idag vill jag prata om en av de längsta filosofiska debatterna: Vad kom först, hönan eller ägget?",
    tr: "Merhaba. Bugün en uzun süreli filozofik tartışmalardan biri hakkında konuşmak istiyorum: Önce tavuk mu yumurta mı geldi?",
    uk: "Доброго дня. Сьогодні я хотів би поговорити про одну з найдавніших філософських дискусій: Що було раніше — курка чи яйце?",
    vi: "Xin chào. Hôm nay tôi muốn nói về một trong những cuộc tranh luận triết học lâu đời nhất: Cái nào có trước, gà hay trứng?"
  },
}
